export const DEFAULT_SETTINGS: TDefaultSettings = {
  minimap: "Show",
  breadcrumbs: "Show",
  compass: "Show",
  nodesToShow: "Folders and files",
  boatSpeed: 3.0,
  acceleration: 0.02,
  deceleration: 0.01,
  turnSpeed: 0.02,
  turnDeceleration: 0.05,
  collisionRadius: 100,
  collisionPushStrength: 5,
  volume: 0.3,
  splashScreen: "Show",
} as const;
